import {
  Category,
  Supplier,
  Location,
  Product,
  Inventory,
  InventoryTransaction,
  CashierShift,
  Sale,
  Purchase
} from '../types/database';

export const INITIAL_LOCATION: Location = {
  id: 'loc-001',
  name: 'A-Mart Main Branch',
  address: 'Shop # 12-16, Commercial Market, Main Boulevard',
  is_default: true,
  is_active: true,
  created_at: '2026-01-01T00:00:00Z'
};

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat-bev', name: 'Beverages', description: 'Cold drinks, juices, mineral water & hot beverages', is_active: true },
  { id: 'cat-dai', name: 'Dairy', description: 'Milk, cheese, butter, yogurt & eggs', is_active: true },
  { id: 'cat-bak', name: 'Bakery', description: 'Fresh bread, buns, biscuits & pastries', is_active: true },
  { id: 'cat-snk', name: 'Snacks', description: 'Chips, nuts, chocolates & confectionery', is_active: true },
  { id: 'cat-gro', name: 'Grocery', description: 'Flour, rice, pulses, cooking oils & spices', is_active: true },
  { id: 'cat-hou', name: 'Household', description: 'Detergents, cleaners, tissues & wraps', is_active: true },
  { id: 'cat-per', name: 'Personal Care', description: 'Soaps, shampoos, oral care & cosmetics', is_active: true },
  { id: 'cat-fro', name: 'Frozen Food', description: 'Nuggets, ready-to-fry, peas & ice creams', is_active: true }
];

export const INITIAL_SUPPLIERS: Supplier[] = [
  {
    id: 'sup-001',
    name: 'National Foods Distribution',
    phone: '+92 300 1234567',
    email: 'orders@nationalfoods.com',
    contact_person: 'Tariq Mehmood',
    payment_terms: 'Net 15 Days',
    opening_balance: 0,
    current_balance: 45000,
    status: 'active',
    notes: 'Primary spice & packaged grocery vendor'
  },
  {
    id: 'sup-002',
    name: 'Nestlé Pakistan Ltd',
    phone: '+92 321 9876543',
    email: 'retail-orders@nestle.pk',
    contact_person: 'Salman Khan',
    payment_terms: 'Weekly Cash/Cheque',
    opening_balance: 0,
    current_balance: 78200,
    status: 'active',
    notes: 'Milk packs, juices, cereals & water'
  },
  {
    id: 'sup-003',
    name: 'Unilever Pakistan Retail',
    phone: '+92 333 4567890',
    email: 'b2b@unilever.pk',
    contact_person: 'Farhan Ali',
    payment_terms: 'Net 30 Days',
    opening_balance: 0,
    current_balance: 112000,
    status: 'active',
    notes: 'Personal care & tea bags'
  },
  {
    id: 'sup-004',
    name: 'Sunrise Agro & Grains Co',
    phone: '+92 301 5554321',
    email: 'supply@sunriseagro.com',
    contact_person: 'Rashid Minhas',
    payment_terms: 'Cash On Delivery',
    opening_balance: 0,
    current_balance: 0,
    status: 'active',
    notes: 'Bulk basmati rice, pulses, sugar'
  }
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-001',
    sku: 'BEV-WAT-001',
    barcode: '896400010101',
    name: 'Nestle Pure Life Mineral Water 1.5L',
    category_id: 'cat-bev',
    supplier_id: 'sup-002',
    unit: 'pcs',
    cost_price: 85,
    selling_price: 110,
    min_stock_level: 24,
    max_stock_level: 200,
    tax_rate: 0,
    expiry_tracked: true,
    allow_negative_stock: false,
    is_active: true,
    description: 'Refreshing natural purified drinking water'
  },
  {
    id: 'prod-002',
    sku: 'BEV-COL-002',
    barcode: '896400010102',
    name: 'Coca-Cola Can 330ml Regular',
    category_id: 'cat-bev',
    supplier_id: 'sup-002',
    unit: 'pcs',
    cost_price: 90,
    selling_price: 120,
    min_stock_level: 18,
    max_stock_level: 150,
    tax_rate: 0,
    expiry_tracked: false,
    allow_negative_stock: false,
    is_active: true,
    description: 'Carbonated sparkling beverage'
  },
  {
    id: 'prod-003',
    sku: 'DAI-MLK-001',
    barcode: '896400020101',
    name: 'Nestle Milkpak UHT Milk 1L',
    category_id: 'cat-dai',
    supplier_id: 'sup-002',
    unit: 'pcs',
    cost_price: 275,
    selling_price: 310,
    min_stock_level: 20,
    max_stock_level: 100,
    tax_rate: 0,
    expiry_tracked: true,
    allow_negative_stock: false,
    is_active: true,
    description: 'Rich and creamy pure UHT milk'
  },
  {
    id: 'prod-004',
    sku: 'DAI-BUT-002',
    barcode: '896400020102',
    name: 'Nurpur Salted Butter 200g',
    category_id: 'cat-dai',
    supplier_id: 'sup-002',
    unit: 'pcs',
    cost_price: 360,
    selling_price: 430,
    min_stock_level: 10,
    max_stock_level: 50,
    tax_rate: 0,
    expiry_tracked: true,
    allow_negative_stock: false,
    is_active: true,
    description: 'Pasteurized salted fresh cow milk butter'
  },
  {
    id: 'prod-005',
    sku: 'GRO-RIC-001',
    barcode: '896400030101',
    name: 'Super Kernel Basmati Rice 5kg Bag',
    category_id: 'cat-gro',
    supplier_id: 'sup-004',
    unit: 'pcs',
    cost_price: 1650,
    selling_price: 1950,
    min_stock_level: 8,
    max_stock_level: 40,
    tax_rate: 0,
    expiry_tracked: false,
    allow_negative_stock: false,
    is_active: true,
    description: 'Aromatic aged long grain basmati rice'
  },
  {
    id: 'prod-006',
    sku: 'GRO-OIL-002',
    barcode: '896400030102',
    name: 'Dalda Premium Cooking Oil Pouch 1L',
    category_id: 'cat-gro',
    supplier_id: 'sup-001',
    unit: 'pcs',
    cost_price: 520,
    selling_price: 580,
    min_stock_level: 15,
    max_stock_level: 80,
    tax_rate: 0,
    expiry_tracked: false,
    allow_negative_stock: false,
    is_active: true,
    description: 'Pure refined sunflower and canola blend'
  },
  {
    id: 'prod-007',
    sku: 'GRO-SUG-003',
    barcode: '896400030103',
    name: 'White Refined Fine Sugar 1kg Pack',
    category_id: 'cat-gro',
    supplier_id: 'sup-004',
    unit: 'kg',
    cost_price: 135,
    selling_price: 160,
    min_stock_level: 25,
    max_stock_level: 120,
    tax_rate: 0,
    expiry_tracked: false,
    allow_negative_stock: false,
    is_active: true,
    description: 'Triple refined crystal cane sugar'
  },
  {
    id: 'prod-008',
    sku: 'SNK-CHP-001',
    barcode: '896400040101',
    name: 'Lays Masala Potato Crisps 65g',
    category_id: 'cat-snk',
    supplier_id: 'sup-001',
    unit: 'pcs',
    cost_price: 68,
    selling_price: 90,
    min_stock_level: 20,
    max_stock_level: 120,
    tax_rate: 0,
    expiry_tracked: true,
    allow_negative_stock: false,
    is_active: true,
    description: 'Crunchy potato chips seasoned with authentic spices'
  },
  {
    id: 'prod-009',
    sku: 'BAK-BRD-001',
    barcode: '896400050101',
    name: 'Dawn Family Size Plain Bread 750g',
    category_id: 'cat-bak',
    supplier_id: 'sup-001',
    unit: 'pcs',
    cost_price: 150,
    selling_price: 180,
    min_stock_level: 12,
    max_stock_level: 40,
    tax_rate: 0,
    expiry_tracked: true,
    allow_negative_stock: false,
    is_active: true,
    description: 'Soft and fresh daily sliced white bread'
  },
  {
    id: 'prod-010',
    sku: 'PER-SHP-001',
    barcode: '896400060101',
    name: 'Sunsilk Black Shine Shampoo 370ml',
    category_id: 'cat-per',
    supplier_id: 'sup-003',
    unit: 'pcs',
    cost_price: 640,
    selling_price: 760,
    min_stock_level: 6,
    max_stock_level: 30,
    tax_rate: 0,
    expiry_tracked: false,
    allow_negative_stock: false,
    is_active: true,
    description: 'Enriched with Amla oil pearl complex'
  },
  {
    id: 'prod-011',
    sku: 'HOU-DET-001',
    barcode: '896400070101',
    name: 'Surf Excel Washing Powder 1kg Pouch',
    category_id: 'cat-hou',
    supplier_id: 'sup-003',
    unit: 'pcs',
    cost_price: 520,
    selling_price: 610,
    min_stock_level: 10,
    max_stock_level: 60,
    tax_rate: 0,
    expiry_tracked: false,
    allow_negative_stock: false,
    is_active: true,
    description: 'Superior stain removal washing powder'
  },
  {
    id: 'prod-012',
    sku: 'FRO-NUG-001',
    barcode: '896400080101',
    name: 'K&Ns Crispy Chicken Nuggets 500g',
    category_id: 'cat-fro',
    supplier_id: 'sup-001',
    unit: 'pcs',
    cost_price: 880,
    selling_price: 1050,
    min_stock_level: 8,
    max_stock_level: 35,
    tax_rate: 0,
    expiry_tracked: true,
    allow_negative_stock: false,
    is_active: true,
    description: 'Breaded chicken breast nuggets deep freeze'
  }
];

export const INITIAL_INVENTORY: Record<string, Inventory> = {
  'prod-001': { id: 'inv-001', product_id: 'prod-001', location_id: 'loc-001', quantity: 64, reserved_quantity: 0, updated_at: new Date().toISOString() },
  'prod-002': { id: 'inv-002', product_id: 'prod-002', location_id: 'loc-001', quantity: 42, reserved_quantity: 0, updated_at: new Date().toISOString() },
  'prod-003': { id: 'inv-003', product_id: 'prod-003', location_id: 'loc-001', quantity: 14, reserved_quantity: 0, updated_at: new Date().toISOString() }, // LOW STOCK! (min 20)
  'prod-004': { id: 'inv-004', product_id: 'prod-004', location_id: 'loc-001', quantity: 5, reserved_quantity: 0, updated_at: new Date().toISOString() },  // LOW STOCK! (min 10)
  'prod-005': { id: 'inv-005', product_id: 'prod-005', location_id: 'loc-001', quantity: 22, reserved_quantity: 0, updated_at: new Date().toISOString() },
  'prod-006': { id: 'inv-006', product_id: 'prod-006', location_id: 'loc-001', quantity: 28, reserved_quantity: 0, updated_at: new Date().toISOString() },
  'prod-007': { id: 'inv-007', product_id: 'prod-007', location_id: 'loc-001', quantity: 0, reserved_quantity: 0, updated_at: new Date().toISOString() },  // OUT OF STOCK!
  'prod-008': { id: 'inv-008', product_id: 'prod-008', location_id: 'loc-001', quantity: 55, reserved_quantity: 0, updated_at: new Date().toISOString() },
  'prod-009': { id: 'inv-009', product_id: 'prod-009', location_id: 'loc-001', quantity: 8, reserved_quantity: 0, updated_at: new Date().toISOString() },  // LOW STOCK! (min 12)
  'prod-010': { id: 'inv-010', product_id: 'prod-010', location_id: 'loc-001', quantity: 16, reserved_quantity: 0, updated_at: new Date().toISOString() },
  'prod-011': { id: 'inv-011', product_id: 'prod-011', location_id: 'loc-001', quantity: 34, reserved_quantity: 0, updated_at: new Date().toISOString() },
  'prod-012': { id: 'inv-012', product_id: 'prod-012', location_id: 'loc-001', quantity: 18, reserved_quantity: 0, updated_at: new Date().toISOString() }
};

export const INITIAL_TRANSACTIONS: InventoryTransaction[] = [
  {
    id: 'tx-001',
    product_id: 'prod-001',
    location_id: 'loc-001',
    transaction_type: 'initial_stock',
    quantity: 100,
    previous_quantity: 0,
    new_quantity: 100,
    unit_cost: 85,
    user_id: 'usr-admin',
    reason: 'Initial stock intake for store launch',
    created_at: '2026-03-01T08:00:00Z'
  },
  {
    id: 'tx-002',
    product_id: 'prod-001',
    location_id: 'loc-001',
    transaction_type: 'sale',
    quantity: -36,
    previous_quantity: 100,
    new_quantity: 64,
    unit_cost: 85,
    related_sale_id: 'sale-001',
    user_id: 'usr-cashier',
    reason: 'POS Sale #SL-20260301-00001',
    created_at: '2026-03-01T14:30:00Z'
  },
  {
    id: 'tx-003',
    product_id: 'prod-003',
    location_id: 'loc-001',
    transaction_type: 'damage',
    quantity: -2,
    previous_quantity: 16,
    new_quantity: 14,
    unit_cost: 275,
    user_id: 'usr-admin',
    reason: 'Pouch puncture during carton unboxing',
    created_at: '2026-03-02T10:15:00Z'
  },
  {
    id: 'tx-004',
    product_id: 'prod-007',
    location_id: 'loc-001',
    transaction_type: 'sale',
    quantity: -40,
    previous_quantity: 40,
    new_quantity: 0,
    unit_cost: 135,
    user_id: 'usr-cashier',
    reason: 'Bulk walk-in customer checkout',
    created_at: '2026-03-02T12:00:00Z'
  }
];

export const INITIAL_SHIFT: CashierShift = {
  id: 'shift-current',
  cashier_id: 'usr-cashier',
  opening_cash: 5000,
  opened_at: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
  cash_sales: 12450,
  card_sales: 8200,
  other_sales: 1500,
  total_returns: 310,
  status: 'open',
  notes: 'Morning shift active'
};
